
version: '2.1'

services:
  
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 10s
      retries: 4
      
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    
  customer-managment:
    image: danielleinov/customer-managment:latest
    environment:
      MONGO_CONNECTION: mongodb://root:example@mongo:27017
      KAFKA_CONNECTION: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    links: 
      - kafka

  customer-facing:
    image: danielleinov/customer-facing:latest
    ports:
      - 5050:5050
    environment:
      CUSTOMER_URL: http://customer-managment:5000
      KAFKA_CONNECTION: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    links: 
      - kafka

